config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to => 'application#index'
  post '/signin' => 'sessions#create'
  get '/signin' => 'sessions#new'
  get '/logout' => 'sessions#destroy'
  get '/auth/facebook/callback' => 'session#create'
  delete '/posts/:id', to: 'posts#destroy'

  resources :posts, only: [:index, :show, :new, :create, :edit, :update]
  resources :users, only: [:index, :show, :new, :create, :edit] do
    resources :reptiles, only: [:show, :index, :new, :edit]
  end
  resources :reptiles, only: [:index, :show, :new, :create, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :reptile
  validates :title, presence: true
  validates :content, presence: true

  def self.from_today
    where("created_at >=?", Time.zone.today.beginning_of_day)
  end

  def self.older
    where("created_at <=?", Time.zone.today.beginning_of_day)
  end
end

app/models/reptile.rb
class Reptile < ApplicationRecord
  belongs_to :user
  has_many :posts
  validates :name, presence: true
  validates :species, presence: true
  validates :offspring, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :reptiles
  has_many :posts, through: :reptiles
  validates :name, presence: true
  validates :name, length: { in: 2..30 }
  validates :email, uniqueness: true
  validates :email, presence: true
  validates :pet_count, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  helper_method :current_user

  def index
    render 'welcome/index'
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  def index
    if !params[:date].blank?
      if params[:date] == "Today"
        @posts = Post.from_today
      else @posts = Post.older
      end
    else
      if params[:user_id]
        @posts = Post.find(params[:user_id]).posts
      else
        @posts = Post.all
      end
    end
  end

  def new
    @post = Post.new
    @reptiles = current_user.reptiles
  end

  def create
    @post = Post.new(post_params)
    if @post.valid?
      @post.save
      redirect_to post_path(@post)
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    @post.update(post_params)
    redirect_to post_path(@post)
  end

  def destroy
    @post.destroy
    redirect_to posts_url
  end

  private

  def post_params
    params.require(:post).permit(:content, :title, :reptile_id)
  end

  def set_post
    @post = Post.find(params[:id])
  end
end

app/controllers/reptiles_controller.rb
class ReptilesController < ApplicationController

  def index
    if params[:user_id]
      @reptiles = User.find(params[:user_id]).reptiles
    else
      @reptiles = Reptile.all
    end
  end

  def show
    # @user = User.find(params[:id])
    @reptile = Reptile.find(params[:id])
  end

  def new
    @reptile = Reptile.new
  end

  def create
    @reptile = Reptile.new(reptile_params)
    @user = current_user
    @reptile.user_id = @user.id
    if @reptile.valid?
      @reptile.save
      redirect_to reptile_path(@reptile)
    else
      render :new
    end
  end

  def edit
    @reptile = Reptile.find(params[:id])
  end

  def update
    @reptile = Reptile.find(params[:id])
    @reptile.update(reptile_params)
    redirect_to reptile_path(@reptile)
  end

  private

  def reptile_params
    params.require(:reptile).permit(:name, :species, :age, :offspring)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @users = User.all
  end

  def create
    @user = User.find_by(email: params[:email])
    return head(:forbidden) unless @user.authenticate(params[:password])
    session[:user_id] = @user.id
    redirect_to @user
  end

  def destroy
    session[:user_id] = nil

    redirect_to '/'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_login, only: :show

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.valid?
      @user.save
      log_in(@user)
      redirect_to users_path(@user)
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
    redirect_to user_path(@user)
  end

  private

  def user_params
    params.require(:user).permit(:name, :pet_count, :email, :password)
  end

  def require_login
    if !logged_in?
      redirect_to '/'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  def logged_in?
    !current_user.nil?
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ReptileApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">Reptile Manager</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item active">
          <a class="nav-link" href=<%=user_path(current_user)%>>Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/reptiles">Reptiles</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/posts">Posts</a>
        </li>
      </ul>
    </div>
  </nav>
  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">


<body>
 <div class="container" align="center">
<h3>Edit your Post</h3>
<%= form_for @post do |f| %>
  <%= f.label :title %></br>
  <%= f.text_area :title %></br>
  </br>
  <%= f.label :content %></br>
  <%= f.text_area :content %></br>
  </br>
  <%= f.submit %>
<% end %>
</div>
</body>

app/views/posts/index.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">


<body>
 <div class="container" align="center">
   <div>
     <h4>Filter Posts</h4>
     <%= form_tag("/posts", method: "get") do %>
       <%= select_tag "date", options_for_select(["Today", "Older"]), include_blank: true %>
       <%= submit_tag "Filter" %>
     <% end %>
   </div>
<h2>Your Posts</h2>
</br>
<% @posts.each do |post| %>
  <div><strong><%= post.title %></div></strong>
  <div><%= post.content %></div>
</br>
<%= link_to 'Edit Post', edit_post_path(post) %></br>
<%= link_to 'View Post', post_path(post) %></br>
</br>
</br>
<% end %>


<%= link_to 'Create New Post', new_post_path %></br>
<%= link_to 'Return to User Page', user_path(current_user) %>
</div>
</body>

app/views/posts/new.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">


<body>
 <div class="container" align="center">
   <% if @post.errors.any? %>
   <div id="error_explanation">
     <h2>
       Oops! Please fix the following errors:
     </h2>

     <ul>
     <% @post.errors.full_messages.each do |msg| %>
       <%= msg %></br>
     <% end %>
     </ul>
   </div>
 <% end %>
<h3>Make a Post</h3>
<%= form_for @post do |f| %>
  <p> Who is your post for?</p>
  <%= f.collection_select :reptile_id, @reptiles, :id, :name %></br>
  <%= f.label :title %></br>
  <%= f.text_area :title %></br>
  </br>
  <%= f.label :content %></br>
  <%= f.text_area :content %></br>
  </br>
  <%= f.submit "Post"%>
<% end %>
</div>
</body>

app/views/posts/show.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">


<body>
<div class="container" align="center">
<div>
<h2><%= @post.title %></h2>
<h4><%= @post.content %></h4>

<%= link_to 'Edit Post', edit_post_path %></br>
<%= link_to 'Delete', method: :delete, data: {confirm: "Are you Sure?" } %></br>
<%= link_to 'See all Posts', posts_path %></br>
<%= link_to 'Return to User Page', user_path(current_user) %>
</div>

app/views/reptiles/edit.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">


<body>
<div class="container" align="center">
<div>
<h3>Make some Changes to your Reptile</h3>
<%= form_for @reptile do |f| %>
  <%= f.label :name %></br>
  <%= f.text_field :name %></br>
  </br>
  <%= f.label :age %></br>
  <%= f.text_field :age %></br>
  </br>
  <%= f.label :species %></br>
  <%= f.text_field :species %></br>
  </br>
  <%= f.label :offspring, "Number of Offspring" %></br>
  <%= f.text_field :offspring %></br>
  </br>
  <%= f.submit %>
<% end %>
</div>

app/views/reptiles/index.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">


<body>
<div class="container" align="center">
<div>
  <h4>Filter Reptiles</h4>
  <%= form_tag("/reptiles", method: "get") do %>
    <%= select_tag "species", options_from_collection_for_select(Reptile.all, "id", "species"), include_blank: true %>
    <%= submit_tag "Filter" %>
  <% end %>
</div>
<h2>Your Reptiles</h2>
</br>
<% @reptiles.each do |reptile| %>
  <div><%= reptile.name %></div>
  <div>Age: <%= reptile.age %></div>
  <div>Species: <%= reptile.species %></div>
  <div>Offspring: <%= reptile.offspring %></div>
  </br>
  <%= link_to 'Edit Reptile', edit_user_reptile_path(reptile.user, reptile) %></br>
  <%= link_to 'View Reptile', user_reptile_path(reptile.user, reptile) %></br>
  </br>
<% end %>
<%= link_to 'Return to User Page', user_path(current_user) %></br>
</div>

app/views/reptiles/new.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">


<body>
<div class="container" align="center">
  <% if @reptile.errors.any? %>
  <div id="error_explanation">
    <h2>
      Oops! Please fix the following errors:
    </h2>

    <ul>
    <% @reptile.errors.full_messages.each do |msg| %>
      <%= msg %></br>
    <% end %>
    </ul>
  </div>
<% end %>
<h3>Create Your Reptile</h3>
<%= form_for @reptile do |f| %>
  <%= f.label :name %></br>
  <%= f.text_field :name %></br>
  </br>
  <%= f.label :age %></br>
  <%= f.text_field :age %></br>
  </br>
  <%= f.label :species %></br>
  <%= f.text_field :species %></br>
  </br>
  <%= f.label :offspring, "Number of Offspring" %></br>
  <%= f.text_field :offspring %></br>
  </br>
  <%= f.submit %>
<% end %>
</div>

app/views/reptiles/show.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">


<body>
<div class="container" align="center">
<div>
<h2><%= @reptile.name %></h2>
<p>Age: <%= @reptile.age %></p>
<p>Species: <%= @reptile.species %></p>
<p>Number of Offspring: <%= @reptile.offspring %></p>

<h3><%= @reptile.name %>'s Posts</h3>
<% @reptile.posts.each do |post| %>
  <strong><%= post.title %></strong></br>
  <%= post.content %></br>
<% end %>
</br>

<%= link_to 'Edit Reptile', edit_reptile_path %></br>
<%= link_to 'See All Reptiles', user_reptiles_path(@reptile.user, @reptiles) %></br>
<%= link_to 'Return to User Page', user_path(current_user) %></br>
</div>

app/views/users/edit.html.erb
<h3>Edit</h3>
<%= form_for @user do |f| %>
  <%= f.label :name %></br>
  <%= f.text_field :name %></br>
  <%= f.label :pet_count, "How many reptiles do you have?" %>
  <%= f.text_field :pet_count %></br>
  <%= f.label :password %></br>
  <%= f.text_field :password %></br>
  </br>
  <%= f.submit %>
<% end %>

app/views/users/index.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">


<body>
 <div class="container" align="center">
<h1> Welcome, <%= @user.name %>!</h1>

<p>Reptiles Owned: <%= @user.pet_count %></p>
</br>
<p><%= link_to 'See Your Posts', posts_path(@posts) %></p>
<p><%= link_to 'Create a New Post', new_post_path %></p>
<p><%= link_to 'See Your Reptiles', reptiles_path(@reptiles) %></p>
<p><%= link_to 'Create a New Reptile', new_reptile_path %></p>
<p><%= link_to 'Logout', logout_path %></p>
</div>
<div class="col-md-12" align="right">
  <div class="sidebar">
    <% @user.posts.each do |post| %>
      <div><%= post.title %></div>
      <div><%= post.content %></div>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">


<body>
<div class="container" align="center">
  <h3>Sign Up!</h3>
  <%= form_for @user do |f| %>
    <%= f.label :email %></br>
    <%= f.text_field :email %></br>
    </br>
    <%= f.label :name %></br>
    <%= f.text_field :name %></br>
    </br>
    <%= f.label :pet_count, "How many reptiles do you have?" %></br>
    <%= f.text_field :pet_count %></br>
    </br>
    <%= f.label :password %></br>
    <%= f.text_field :password %></br>
    </br>
    <%= f.submit %>
  <% end %>
</div>

app/views/users/show.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">


<body>
 <div class="container" align="center">
<h1> Welcome, <%= @user.name %>!</h1>

<p>Reptiles Owned: <%= @user.pet_count %></p>
</br>
<p><%= link_to 'See Your Posts', posts_path(@posts) %></p>
<p><%= link_to 'Create a New Post', new_post_path %></p>
<p><%= link_to 'See Your Reptiles', reptiles_path(@reptiles) %></p>
<p><%= link_to 'Create a New Reptile', new_reptile_path %></p>
<p><%= link_to 'Logout', logout_path %></p>
</div>
<div class="col-md-12" align="right">
  <div class="sidebar">
    <% @user.posts.each do |post| %>
      <div><%= post.title %></div>
      <div><%= post.content %></div>
    <% end %>
  </div>
</div>

app/views/welcome/index.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">


<body>
 <div class="container" align="center">
   <h2>Please Click Below to Login</h2>
   <%= link_to 'Log In', '/signin' %></br>
   <%= link_to 'Log In with Facebook!', '/auth/facebook' %>

   <h4>
     <medium class="text-muted"> No account? Sign Up!</medium>
   </h4>
   <%= link_to 'Sign Up', '/users/new' %>
 </div>
</body>